### ISSUE TITLE
Hash incorrect

### ISSUE THREAD

**Issue by jniemin** [chrisveness/latlon-geohash#2]
Seems that when encoding location with coordinates latitude:37.25 longitude: 123.75 outcome is 'wwxgzvpuzzrc'. If I calculate same coordinates with PostGIS the hash is 'wy85bj0hbp21'. Also geohash.org gives same 'wy85bj0' hash for the coordinates, see http://geohash.org/wy85bj0

**Comment by chrisveness** [comment]
It seems geohash.org uses '>=' comparisons in the encode bisect operation, rather than (the more commonly seen) '>'.

I have updated the comparisons to match geohash.org.
