### ISSUE TITLE
InvalidValueError: setBounds: and InvalidValueError: setCenter:

### ISSUE THREAD

**Issue by Sarahphp1** [chrisveness/latlon-geohash#5]
Hi
Do you know why I am getting the following errors when using Geohash.bounds() and Geohash.decode() respectively:

InvalidValueError: setBounds: not a LatLngBounds or LatLngBoundsLiteral: in property south: not a number
InvalidValueError: setCenter: not a LatLng or LatLngLiteral: in property lng: not a number

Thanks

**Comment by chrisveness** [comment]
I think those errors are coming from Google Maps, not from Geohash.

See [developers.google.com/maps/documentation/javascript/reference/polygon#Rectangle.setBounds](https://developers.google.com/maps/documentation/javascript/reference/polygon#Rectangle.setBounds).

Note that the bounds used in Geohash is similar to, but not identical to, the Google Maps `LatLngBounds` object.

**Comment by Sarahphp1** [comment]
Thanks for your prompt response..
Yes, I refer to google API all the time.
Bounds in Geohash are numbers though, yes? 
but what do mean by 'not identical' ?

Anyway, it turns out that it was loading problem. The values of lat and lng values are undefined at initial page load.
