### ISSUE TITLE
Add option to show base4 instead base32

### ISSUE THREAD

**Issue by ppKrauss** [chrisveness/latlon-geohash#6]
The structure of the Geohash is a base4 hierarchy: powers of 4 in the spatial representation &mdash; the grid cell divided into 4 cels each iteration, as a complete Z-order curve and lat-long analogus.

In applications that need to access "the full hierarchy", is important to use base4 (2 bits). In the Javascript code is only a inclusion of one parameter in the Encode method:

* @param   {number} lat - Latitude in degrees.
* @param   {number} lon - Longitude in degrees.
* @param   {number} [precision] - Number of characters in resulting geohash.
* @param {boolean} [useBase4] - Flag to use base4 instead base32 (default is false)

```js
Geohash.encode = function(lat, lon, precision, useBase4) {
...
var maxBits = (useBase4===true)? 2: 5;
...
        if (++bit == maxBits) {
            // maxBits bits gives us the base 2^maxBits character
           ...
      }
...
```

**Comment by chrisveness** [comment]
This is quite simple to achieve using parseInt(), e.g.

    const geohash = Geohash.encode(52.20, 0.12, 6); // 'u120fw'
    parseInt(geohash, 32).toString(4);              // '1320020200033'

Since this is straightforward, I don't think it is worth an extra argument to encode() & decode().

I've added a note about Base4 to the README.

**Comment by ppKrauss** [comment]
Hi, remember that `parseInt` not works with more tham ~50 bits, for 64 bits we need [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)... And, of course, it is **bad practice for CPU time**, simple and direct maxBits is better.
