### ISSUE TITLE
Geohash.neighbours with a given radius in km.

### ISSUE THREAD

**Issue by shuzootani** [chrisveness/latlon-geohash#7]
Thanks, your library helps me a lot.
I'm trying to search data within a certain radius in km.
and I wonder if I could do like

```
Geohash.neighbours(geohash, radius, { units: km })
```

Is there any way to get array of geohash for a grid in a given radius?

```
input: geohash, radius(km)
output: [geohash1, geohash2, ...] that is a grid(circle or polygon) representing a given radius.
```

Thank you

**Comment by smarcosanderson** [comment]
Well, just arrived here, but answering your question...
take a look on this page: https://www.movable-type.co.uk/scripts/geohash.html

Seems like you just need to increase/decrease the precision for the encode..
Depending on your precision, more specific or general will be your location.

So two persons in a range of 15km, would have the same geocode if you pass a lower precision (4 for example). but would have different geocode if you pass a higher precision (8 as example).

**Comment by chrisveness** [comment]
Thanks for that explanation @smarcosanderson.
